[build]
  publish = "_site"
  command = "DEBUG=* eleventy"

[[redirects]]
  from = "/micropub"  
  to = "https://irreverent-style-micropub.netlify.app/.netlify/functions/micropub"
  status = 200
  force = true